### ISSUE TITLE
i have a question 

### ISSUE THREAD

**Issue by wangzilong1997** [mrd1no/poster-0.8.1-for-Python-3.4#3]
when i run a .py  with your poster 
but i can this err i can not should do
can you help me 
thinks
Errer message:
Traceback (most recent call last):
  File "media.py", line 29, in <module>
    myMedia.uplaod(accessToken,filePath,mediaType)
  File "media.py", line 16, in uplaod
    postData,postHeaders = poster.encode.multipart_encode(param)
  File "/usr/local/lib/python3.5/dist-packages/poster-0.8.1-py3.5.egg/poster/encode.py", line 411, in multipart_encode
  File "/usr/local/lib/python3.5/dist-packages/poster-0.8.1-py3.5.egg/poster/encode.py", line 311, in get_headers
  File "/usr/local/lib/python3.5/dist-packages/poster-0.8.1-py3.5.egg/poster/encode.py", line 302, in get_body_size
  File "/usr/local/lib/python3.5/dist-packages/poster-0.8.1-py3.5.egg/poster/encode.py", line 177, in from_params
  File "/usr/local/lib/python3.5/dist-packages/poster-0.8.1-py3.5.egg/poster/encode.py", line 94, in __init__
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by wangzilong1997** [comment]
if you have any idea must tell me
